### ISSUE TITLE
Getting data

### ISSUE THREAD

**Issue by vladutcoman** [nnyegaard/AspCoreSocialLoginExample#1]
Do you know how I can get profile data/fields using this aproach for authentification?

**Comment by nnyegaard** [comment]
Do you mean from the different providers?

You can add the fields you want on the scope object, and you will then have access to it from the context.
There is an example of that in the code.

**Comment by vladutcoman** [comment]
Yeah, I try it and it works.
Thank you for the reply!

**Comment by vladutcoman** [comment]
Hello,

thanks for the replie, I did like you said it works!

2017-07-28 16:30 GMT+03:00 Nicklas Nyegaard <notifications@github.com>:

**Comment by nnyegaard** [comment]
I'm glade it worked.
